### ISSUE TITLE
Giving a var the same name as the function that it is in

### ISSUE THREAD

**Issue by dannyech** [alexandramedway/odds#70] opened 2015-12-01 04:47 UTC
This throws a random error (that we are not catching):
```ocaml
do sum = (x, y) - >
  do sum = x + y
  return sum
```
The error occurs when we give a var the same name as the function that it is in. I think it's fair to  just prohibit this behavior by the user, but we ought to be able to catch this error and print an actual error statement.

**Comment by akalicki** [comment] 2015-12-01 05:39
Without looking too much into it, I think the issue is that we're reassigning sum in the scope to a Num from a Func type. Then we try to constrain in some way and it gets confused?

**Comment by akalicki** [comment] 2015-12-01 06:54
Yep that's what's happening. `sum` gets assigned to a num, then we attempt to lookup the func type to resolve params and it's no longer a function type. I think the easiest thing to do is just print the error statement as well.

**Comment by akalicki** [comment] 2015-12-01 07:21
I think I caught all cases (reassigning to func, reassigning to other types) in 7b1c191b8f1125df7f5efcfdda12150f81c4e8c0, let me know if there's anything more you see!

**Closed** 2015-12-02 09:45 UTC
Labels: bug, compiler
